-- Calendar days become dates (outfit_calendar.date timestamptz -> day date).
-- Generated by drizzle-kit (rename, index and constraint changes); the
-- guard, the type conversion and the de-duplication are hand-written.
--
-- Guard: every build before this one wrote UTC midnight (new Date('YYYY-MM-DD')),
-- so the conversion below keeps each row's day. A value that is not UTC
-- midnight means that assumption is wrong for this database: abort (the
-- whole batch rolls back and the boot fails) instead of moving a planned
-- outfit to another day. notes was never written by any form; a row that has
-- one aborts too rather than lose it.
DO $$
DECLARE
  off_midnight integer;
  with_notes integer;
BEGIN
  SELECT count(*) INTO off_midnight FROM "outfit_calendar"
    WHERE ("date" AT TIME ZONE 'UTC')::time <> time '00:00';
  IF off_midnight > 0 THEN
    RAISE EXCEPTION 'outfit_calendar: % row(s) have a date that is not UTC midnight; converting them to a day would guess. Fix those rows, then boot again.', off_midnight;
  END IF;
  SELECT count(*) INTO with_notes FROM "outfit_calendar" WHERE "notes" IS NOT NULL;
  IF with_notes > 0 THEN
    RAISE EXCEPTION 'outfit_calendar: % row(s) have notes, which this migration drops. Move them elsewhere, clear them, then boot again.', with_notes;
  END IF;
END $$;--> statement-breakpoint
DROP INDEX "outfit_calendar_date_index";--> statement-breakpoint
DROP INDEX "outfit_calendar_owner_id_index";--> statement-breakpoint
ALTER TABLE "outfit_calendar" RENAME COLUMN "date" TO "day";--> statement-breakpoint
ALTER TABLE "outfit_calendar" ALTER COLUMN "day" SET DATA TYPE date USING ("day" AT TIME ZONE 'UTC')::date;--> statement-breakpoint
ALTER TABLE "outfit_calendar" DROP COLUMN "notes";--> statement-breakpoint
-- Repeated saves of the outfit form scheduled the same outfit on the same day
-- more than once. Keep one row per (owner, day, outfit), preferring a row
-- marked worn, then the oldest, so the unique constraint below can hold.
DELETE FROM "outfit_calendar" WHERE "id" IN (
  SELECT "id" FROM (
    SELECT "id", row_number() OVER (
      PARTITION BY "owner_id", "day", "outfit_id"
      ORDER BY "worn_at" IS NULL, "id"
    ) AS "rank"
    FROM "outfit_calendar"
  ) AS "ranked"
  WHERE "rank" > 1
);--> statement-breakpoint
ALTER TABLE "outfit_calendar" ADD CONSTRAINT "outfit_calendar_owner_id_day_outfit_id_unique" UNIQUE("owner_id","day","outfit_id");
