-- Outfit composition gets one store: outfit_slot (one row per builder row,
-- ordered, a category and an optional garment) replaces outfit.slots (JSON,
-- the order and the empty rows) and outfit_garments (the pivot, unordered,
-- which the pages rendered). The two disagreed by construction; see
-- docs/audits/2026-09-25-program2, datamodel 1.5.
-- Generated by drizzle-kit (table, keys, index, the drops); the guard, the
-- backfill and the verification are hand-written, and the drops moved last.
--
-- Guard: the JSON must be the shape every build wrote, an array of
-- {category, garmentId} objects (or null), or the backfill below would have
-- to guess. Anything else aborts the boot (the whole batch rolls back).
DO $$
DECLARE
  not_arrays integer;
  without_category integer;
BEGIN
  SELECT count(*) INTO not_arrays FROM "outfit"
    WHERE "slots" IS NOT NULL AND jsonb_typeof("slots") NOT IN ('array', 'null');
  IF not_arrays > 0 THEN
    RAISE EXCEPTION 'outfit.slots: % row(s) hold something other than an array of slots. Fix those rows, then boot again.', not_arrays;
  END IF;
  SELECT count(*) INTO without_category
    FROM "outfit", jsonb_array_elements(
      CASE WHEN jsonb_typeof("slots") = 'array' THEN "slots" END
    ) AS "slot"
    WHERE jsonb_typeof("slot" -> 'category') IS DISTINCT FROM 'string';
  IF without_category > 0 THEN
    RAISE EXCEPTION 'outfit.slots: % slot(s) have no category. Fix those rows, then boot again.', without_category;
  END IF;
END $$;--> statement-breakpoint
CREATE TABLE "outfit_slot" (
	"outfit_id" integer NOT NULL,
	"position" smallint NOT NULL,
	"category" text NOT NULL,
	"garment_id" integer,
	CONSTRAINT "outfit_slot_pkey" PRIMARY KEY("outfit_id","position")
);
--> statement-breakpoint
ALTER TABLE "outfit_slot" ADD CONSTRAINT "outfit_slot_outfit_id_foreign" FOREIGN KEY ("outfit_id") REFERENCES "public"."outfit"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "outfit_slot" ADD CONSTRAINT "outfit_slot_garment_id_foreign" FOREIGN KEY ("garment_id") REFERENCES "public"."garment"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "outfit_slot_garment_id_index" ON "outfit_slot" USING btree ("garment_id");--> statement-breakpoint
-- The slots as saved, in array order. A slot keeps its garment only if that
-- garment still exists and belongs to the outfit's owner: the JSON kept ids
-- of deleted garments (no foreign key) and, from hand-made requests, ids the
-- pivot had refused. Such a slot stays, empty, as the builder would show it.
-- The regex keeps a malformed id (a fraction, a string) from failing the cast.
-- A null (SQL or JSON) slots value yields no rows; the CASE keeps the function
-- from ever seeing one, whatever order the planner applies conditions in.
INSERT INTO "outfit_slot" ("outfit_id", "position", "category", "garment_id")
SELECT "outfit"."id",
       ("slot"."ordinality" - 1)::smallint,
       "slot"."value" ->> 'category',
       "garment"."id"
FROM "outfit"
CROSS JOIN LATERAL jsonb_array_elements(
  CASE WHEN jsonb_typeof("outfit"."slots") = 'array' THEN "outfit"."slots" END
) WITH ORDINALITY AS "slot"("value", "ordinality")
LEFT JOIN "garment"
  ON "garment"."owner_id" = "outfit"."owner_id"
 AND "garment"."id" = CASE
       WHEN "slot"."value" ->> 'garmentId' ~ '^[0-9]{1,9}$'
       THEN ("slot"."value" ->> 'garmentId')::integer
     END;--> statement-breakpoint
-- Outfits with pivot rows but no slots (saved before the builder stored
-- slots, or with an empty array): one slot per pivot garment of the owner's,
-- ordered by category, then garment id.
INSERT INTO "outfit_slot" ("outfit_id", "position", "category", "garment_id")
SELECT "pivot"."outfit_id",
       (row_number() OVER (
         PARTITION BY "pivot"."outfit_id"
         ORDER BY "garment"."category", "garment"."id"
       ) - 1)::smallint,
       "garment"."category",
       "garment"."id"
FROM "outfit_garments" AS "pivot"
JOIN "outfit" ON "outfit"."id" = "pivot"."outfit_id"
JOIN "garment" ON "garment"."id" = "pivot"."garment_id"
  AND "garment"."owner_id" = "outfit"."owner_id"
WHERE NOT EXISTS (
  SELECT 1 FROM "outfit_slot" WHERE "outfit_slot"."outfit_id" = "pivot"."outfit_id"
);--> statement-breakpoint
-- Verify before dropping anything: per outfit, the garments in its slots must
-- be exactly its pivot garments (both owner-checked). Compared as sets, not
-- counts, so a swapped garment is caught and a garment the user put in two
-- rows (two slots, one pivot row) is not a false alarm. A difference means
-- dropping the pivot would lose a garment the pages showed, or the slots name
-- one they never did: abort the boot and leave both stores as they are.
DO $$
DECLARE
  mismatched integer;
  outfit_ids text;
BEGIN
  WITH "pivot" AS (
    SELECT "outfit_garments"."outfit_id", "outfit_garments"."garment_id"
    FROM "outfit_garments"
    JOIN "outfit" ON "outfit"."id" = "outfit_garments"."outfit_id"
    JOIN "garment" ON "garment"."id" = "outfit_garments"."garment_id"
      AND "garment"."owner_id" = "outfit"."owner_id"
  ), "slotted" AS (
    SELECT DISTINCT "outfit_id", "garment_id" FROM "outfit_slot"
    WHERE "garment_id" IS NOT NULL
  ), "difference" AS (
    (SELECT * FROM "pivot" EXCEPT SELECT * FROM "slotted")
    UNION
    (SELECT * FROM "slotted" EXCEPT SELECT * FROM "pivot")
  )
  SELECT count(DISTINCT "outfit_id"),
         string_agg(DISTINCT "outfit_id"::text, ', ')
    INTO mismatched, outfit_ids
    FROM "difference";
  IF mismatched > 0 THEN
    RAISE EXCEPTION 'outfit_slot: % outfit(s) (id %) list different garments in outfit.slots and outfit_garments; dropping them would lose one. Make the two agree for those outfits, then boot again.', mismatched, outfit_ids;
  END IF;
END $$;--> statement-breakpoint
DROP TABLE "outfit_garments";--> statement-breakpoint
ALTER TABLE "outfit" DROP COLUMN "slots";
