-- Garments move to the web layer (src/web/wardrobe/): free text becomes
-- text, the acquisition date a plain date under its correct spelling, share
-- ids unique, the wardrobe grid gets owner-first indexes for its keyset
-- pages, and the never-used columns go (flagged and banned everywhere,
-- file.mimetype, user.shareable_id). See the 2026-09-25 data-model audit,
-- datamodel 1.3, 1.4, 1.7, 2.1 and 3.
-- Generated by drizzle-kit with the column still named date_aquired (a
-- rename needs its TTY prompt), then edited: the rename and its USING, the
-- normalisation and the guards are hand-written. The snapshot is
-- drizzle-kit's own (generateDrizzleJson from src/db/schema.ts), and a
-- second `drizzle-kit generate` finds nothing to do.
--
-- Normalise what the old form stored the way the new one writes it (the
-- server now trims, turns blank optional fields into NULL, lowercases the
-- category and validates colours): nothing a person typed is lost, only
-- blank strings and stray whitespace. Outfit slots name categories too; they
-- follow, or a slot saved as "Tops" would stop cycling through "tops".
UPDATE "garment" SET
  "name" = NULLIF(btrim("name"), ''),
  "brand" = NULLIF(btrim("brand"), ''),
  "size" = NULLIF(btrim("size"), ''),
  "notes" = CASE WHEN btrim("notes") = '' THEN NULL ELSE "notes" END,
  "washing_details" = CASE WHEN btrim("washing_details") = '' THEN NULL ELSE "washing_details" END,
  "category" = lower(btrim("category")),
  "color" = NULLIF(array_to_string(ARRAY(
    SELECT btrim("t"."token")
      FROM unnest(string_to_array("color", ',')) WITH ORDINALITY AS "t"("token", "n")
     WHERE btrim("t"."token") <> ''
     ORDER BY "t"."n"
  ), ','), '');--> statement-breakpoint
UPDATE "outfit_slot" SET "category" = lower(btrim("category"));--> statement-breakpoint
-- Guards: abort (the whole batch rolls back and the boot fails) rather than
-- guess. Every build before this one wrote acquisition dates at UTC midnight
-- (new Date('YYYY-MM-DD')), so the conversion below keeps each day; any
-- other value means that assumption is wrong for this database. A colour
-- outside the GarmentColor set (the old form let people type their own) or
-- a blank category cannot be written by the new form, and dropping either
-- would lose what someone chose. Duplicate share ids would fail the unique
-- indexes below with a less helpful message.
DO $$
DECLARE
  off_midnight integer;
  unknown_colors text;
  blank_categories integer;
  duplicate_shares integer;
BEGIN
  SELECT count(*) INTO off_midnight FROM "garment"
    WHERE ("date_aquired" AT TIME ZONE 'UTC')::time <> time '00:00';
  IF off_midnight > 0 THEN
    RAISE EXCEPTION 'garment: % row(s) have a date_aquired that is not UTC midnight; converting them to a day would guess. Fix those rows, then boot again.', off_midnight;
  END IF;
  SELECT string_agg(DISTINCT "token", ', ' ORDER BY "token") INTO unknown_colors
    FROM "garment", unnest(string_to_array("garment"."color", ',')) AS "token"
    WHERE "token" NOT IN ('red', 'pink', 'orange', 'yellow', 'green', 'blue',
      'purple', 'black', 'white', 'grey', 'beige', 'brown', 'gold', 'silver',
      'pattern', 'other');
  IF unknown_colors IS NOT NULL THEN
    RAISE EXCEPTION 'garment: colours outside the built-in set (%): the garment form no longer accepts them. Replace them (with other, say), then boot again.', unknown_colors;
  END IF;
  SELECT count(*) INTO blank_categories FROM "garment" WHERE "category" = '';
  IF blank_categories > 0 THEN
    RAISE EXCEPTION 'garment: % row(s) have a blank category, which is required. Give them one, then boot again.', blank_categories;
  END IF;
  SELECT (SELECT count(*) - count(DISTINCT "shareable_id") FROM "garment")
       + (SELECT count(*) - count(DISTINCT "shareable_id") FROM "outfit")
       + (SELECT count(*) - count(DISTINCT "shareable_id") FROM "file")
    INTO duplicate_shares;
  IF duplicate_shares > 0 THEN
    RAISE EXCEPTION 'garment, outfit, file: % duplicate shareable_id value(s); a share link would open the wrong item. Give each duplicate a fresh random UUID, then boot again.', duplicate_shares;
  END IF;
END $$;--> statement-breakpoint
DROP INDEX "file_shareable_id_index";--> statement-breakpoint
DROP INDEX "garment_category_index";--> statement-breakpoint
DROP INDEX "garment_owner_id_index";--> statement-breakpoint
DROP INDEX "garment_shareable_id_index";--> statement-breakpoint
DROP INDEX "outfit_shareable_id_index";--> statement-breakpoint
DROP INDEX "user_shareable_id_index";--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "category" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "brand" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "size" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "notes" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "color" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "garment" RENAME COLUMN "date_aquired" TO "acquired_on";--> statement-breakpoint
ALTER TABLE "garment" ALTER COLUMN "acquired_on" SET DATA TYPE date USING ("acquired_on" AT TIME ZONE 'UTC')::date;--> statement-breakpoint
CREATE UNIQUE INDEX "file_shareable_id_unique" ON "file" USING btree ("shareable_id");--> statement-breakpoint
CREATE INDEX "garment_owner_id_archived_id_index" ON "garment" USING btree ("owner_id","archived","id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "garment_owner_id_category_id_index" ON "garment" USING btree ("owner_id","category","id" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "garment_shareable_id_unique" ON "garment" USING btree ("shareable_id");--> statement-breakpoint
CREATE UNIQUE INDEX "outfit_shareable_id_unique" ON "outfit" USING btree ("shareable_id");--> statement-breakpoint
ALTER TABLE "file" DROP COLUMN "flagged";--> statement-breakpoint
ALTER TABLE "file" DROP COLUMN "banned";--> statement-breakpoint
ALTER TABLE "file" DROP COLUMN "mimetype";--> statement-breakpoint
ALTER TABLE "garment" DROP COLUMN "flagged";--> statement-breakpoint
ALTER TABLE "garment" DROP COLUMN "banned";--> statement-breakpoint
ALTER TABLE "outfit" DROP COLUMN "flagged";--> statement-breakpoint
ALTER TABLE "outfit" DROP COLUMN "banned";--> statement-breakpoint
ALTER TABLE "user" DROP COLUMN "shareable_id";--> statement-breakpoint
ALTER TABLE "user" DROP COLUMN "flagged";--> statement-breakpoint
ALTER TABLE "user" DROP COLUMN "banned";
