-- Emails become unique case-insensitively, and outfit names and notes free text.
-- Generated by drizzle-kit (constraint, index and column types); the guard and
-- the lower-casing are hand-written.
--
-- Guard: the app compares emails as normalizeEmail does (trimmed, lower case),
-- but rows from before 2026-09-26 were stored as typed, and the old unique
-- constraint was on the raw column. Two rows that normalize to the same
-- address are two accounts one login cannot tell apart: abort (the whole batch
-- rolls back and the boot fails) rather than guess which one to keep. Merge or
-- rename one of them through pgvault-connect, then boot again.
DO $$
DECLARE
  clashes text;
BEGIN
  SELECT string_agg(ids, '; ') INTO clashes FROM (
    SELECT string_agg("id"::text, ', ' ORDER BY "id") AS ids
    FROM "user"
    WHERE "email" IS NOT NULL
    GROUP BY lower(btrim("email"))
    HAVING count(*) > 1
  ) AS clash;
  IF clashes IS NOT NULL THEN
    RAISE EXCEPTION 'user: accounts share an email once lower-cased (user ids %). Change or merge them, then boot again.', clashes;
  END IF;
END $$;--> statement-breakpoint
-- Every row as normalizeEmail would have written it.
UPDATE "user" SET "email" = lower(btrim("email")) WHERE "email" <> lower(btrim("email"));--> statement-breakpoint
ALTER TABLE "user" DROP CONSTRAINT "user_email_unique";--> statement-breakpoint
ALTER TABLE "outfit" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "outfit" ALTER COLUMN "notes" SET DATA TYPE text;--> statement-breakpoint
CREATE UNIQUE INDEX "user_lower_email_unique" ON "user" USING btree (lower("email"));
